apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
    replicas: 2           #кол-во контейнеров
    strategy:
      type: Recreate      #стратеги€ обновлени€
    selector:             #селектор дл€ поиска УсвоихФ podТов
      matchLabels:
        name: my-app
    template:             #шаблон podТа
      metadata:
        labels:
          name: my-app
      spec:
        containers:
          - name: nginx
            image: nginx:1.12
            ports:
              - containerPort: 80
